### PR TITLE
Added HIConstraints and refactored constraints

### PR DESCRIPTION
**Pull request by kirbec**

### CODE REVIEW

**Comment by rauhul** [comment]
Hey, sorry I wasn't getting notified of PRs for some reason. lmk when you're ready to get this reviewed

**Comment by rauhul** [comment]
Couple things from an initial pass through:
1. Theres no need to create a new class for these methods, you can add them as an extension to UIView
2. Instead of specifying true/false and a value you can use an optional to determine if the constraint should be set and with what values

With these two changes the method changes to:

```swift
internal extension UIView {
    func constrainIn(superView: UIView, topInset: CGFloat?, trailingInset: CGFloat?, bottomInset: CGFloat?, leadingInset: CGFloat?, widthInset: CGFloat?, heightInset: CGFloat?) {
        if let topInset = topInset {
            // handle setting top constraint...
        }
        // etc...
    }
}
```

**Comment by rauhul** [comment]
Also this should be a pr into dev

**Comment by kirbec** [comment]
Is there a specific class that I should put it in? Or can I just jam it into HIMenuController.swift

**Comment by rauhul** [comment]
The appropriate placement would be a new file under the UI folder called `UIViewExtensions.swift`.

**Pull request closed without merging**
