### PR TITLE
Added UIView Extension that shakes any view. This is used to indicate…

### PR DESCRIPTION
**Pull request by lesseradmin**
… login failure.

### CODE REVIEW

**Comment by lesseradmin** [comment]
I moved the function to be an instance method on HIUserPassLoginController. Why is merging still blocked?

**Comment by rauhul** [comment]
1. Its in the wrong file, HILoginFlowController not HIUserPassLoginController
2. It makes the wrong view shake
3. It unnecessarily uses a CABasicAnimation where it could be using a simpler modern abstraction with UIViewPropertyAnimator

**Comment by lesseradmin** [comment]
Everything should be good now.

**Comment by lesseradmin** [comment]
What's wrong now? I thought everything was okay now?

**Pull request merged**
