### PR TITLE
Full width onboarding carousel

### PR DESCRIPTION
**Pull request by RobertPieta**
Onboarding carousel frame updated to full width, while maintaining cell sizing across idioms

### CODE REVIEW

**Comment by m-dierker** [comment]
Can you provide a screenshot and/or screen recording for this?

**Comment by RobertPieta** [comment]
Of course!

simulator_screenshot_D2295707-A7D4-43D0-92FA-C6F149842F4D

simulator_screenshot_D08BCF85-E582-41EA-AB43-281335C929E5

simulator_screenshot_694350F8-D990-49D6-ADB4-107C21C83426

**Review by s0phialiu — DISMISSED** [review]
Looks good to me!

**Review by s0phialiu — APPROVED** [review]
Looks great!

**Pull request merged**
