### PR TITLE
Configured New Tab Bar

### PR DESCRIPTION
**Pull request by jeffkim2001**
The color scheme and icons of the tab bar have been revised for the 2021 app.

### CODE REVIEW

**Review by PatrickKan — CHANGES_REQUESTED** [review]
I don't think you necessarily need to remove the map and project icons, since we'll revert to it again in future years likely, otherwise looks good! And I dont think space is a big worry since the icons are really small anyways, but let me know if you think otherwise

**Comment by rauhul** [comment]
Why not just use SF Symbols for these?

**Comment by PatrickKan** [comment]
Pull from dev to update with CI

**Comment by jeffkim2001** [comment]
New Tab Bar Screenshot:
tab-bar

**Review by PatrickKan — APPROVED** [review]

**Pull request merged**
