### PR TITLE
Bump up deployment target

### LINKED ISSUE #585: Bump up deployment target
App Store requires apps to be built in Xcode 15 for iOS 17. Current deployment target for the app is iOS 14 --> need to bump it up to iOS 17 and handle any deprecations that occur.

### PR DESCRIPTION
**Pull request by anushkasankaran**
Fixes #585 

- Deployment target increase from iOS 14.0 to iOS 17.0.
- Re-added url-image package to fix missing package dependencies.

### CODE REVIEW

**Comment by AydanPirani** [comment]
@anushkasankaran  hmm, is build supposed to be failing?

**Comment by lasyaneti** [comment]
Does local build work? Error looks like an architecture issue but PR diff doesn't touch anything related to that.

**Comment by anushkasankaran** [comment]
Local build was working fine. It was kind of buggy though and I did something irrelevant to most of the build errors and it got rid of all of them.

**Comment by s0phialiu** [comment]
warning: None of the architectures in ARCHS (x86_64) are valid. Consider setting ARCHS to $(ARCHS_STANDARD) or updating it to include at least one value from VALID_ARCHS (arm64, arm64e, armv7, armv7s). (in target 'URLImage' from project 'URLImage')

1. Can you go to Project Settings in Xcode, go to build settings, and see if setting Architectures to $(ARCHS_STANDARD) does anything? 
2. Can you try making a dummy PR with the non-bumped up version and see if there's still a build error?

**Review by s0phialiu — APPROVED** [review]

**Pull request merged**
