### PR TITLE
Enable APS entitlement

### PR DESCRIPTION
**Pull request by redsn0w422**

### CODE REVIEW

**Comment by sujaypat** [comment]
Has this been tested?

**Comment by redsn0w422** [comment]
No it's still in progress, but @PatrickKan said he was missing the entitlement when trying to test.

**Comment by sujaypat** [comment]
@PatrickKan can you rebase off this branch or cherry pick its commits and test? If it works we can merge this branch and you can rebase off dev again

**Comment by PatrickKan** [comment]
@redsn0w422 Ok it builds on a device, now, but the bundle id on stickers has to be "org.hackillinois.ios-2019.stickers", assuming the bundle id for the app is "org.hackillinois.ios-2019".

**Pull request merged**
