### PR TITLE
Adds swipe gesture support for segmented control navigation

### PR DESCRIPTION
**Pull request by RobertPieta**
Swipe left and right navigation for segmented controls adds an intuitive navigation mechanism for home and schedule. Additionally, the schedule will start on the current day.

### CODE REVIEW

**Comment by m-dierker** [comment]
Can you add a screen recording here?

**Comment by RobertPieta** [comment]
Absolutely!

https://user-images.githubusercontent.com/3848659/221395217-7158ba5f-a1e8-48b2-8f16-35376c5e7a19.mp4

**Review by s0phialiu — DISMISSED** [review]
The swipe gesture additions look great, thank you!

**Review by s0phialiu — APPROVED** [review]
lgtm!

**Pull request merged**
